Create a tea bag
Fenrur/instamint pull request #53
Opened 2024-06-07 16:01 UTC by ouafaema

Scrum-35 : As a MINTER, I can create a TEA BAG

2024-06-09 12:05 UTC, sckaper commented
link your code and fix the build first please

2024-06-11 20:29 UTC, fourm1 requested changes
Delete all the commentaries

2024-06-11 22:45 UTC, fourm1 approved these changes
This seems good now

2024-06-12 11:43 UTC, sckaper approved these changes
that's functionnal

2024-06-12 12:16 UTC, merged

2024-07-08 14:42 UTC, avetisk commented on app/api/profile/update/route.ts
> +  //Const formData = await req.formData()
Dead code.

2024-07-08 14:43 UTC, avetisk commented on app/api/tea-bag/get/route.ts
> +// @ts-expect-error TODO fix library not found
You should add the TODO in your issue tracker, not here.

2024-07-08 14:43 UTC, avetisk commented on app/api/tea-bag/route.ts
> +
Use a lib like `zod` or `yup`.

2024-07-08 14:44 UTC, avetisk commented on app/profile/[slug]/ssr.tsx
> +          <TrashIcon className="size-6" color="red"/>
Declare your handlers before using them in JSX.